services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mod-emotor:latest
    container_name: mod-emotor
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
